"""Project detection, .todos.md generation, CLAUDE.md updates."""

from __future__ import annotations

import os
import re
from pathlib import Path

from todo.models import Status, Todo

BEGIN_SENTINEL = "<!-- BEGIN TODO CLI -->"
END_SENTINEL = "<!-- END TODO CLI -->"


def detect_project(cwd: Path, projects_roots: list[str]) -> str | None:
    """Detect project name from cwd based on configured project roots."""
    cwd = cwd.resolve()
    for root in projects_roots:
        root_path = Path(os.path.expanduser(root)).resolve()
        try:
            rel = cwd.relative_to(root_path)
        except ValueError:
            continue
        # First component under the root is the project name
        parts = rel.parts
        if parts:
            return parts[0]
    return None


def generate_todos_md(project_name: str, todos: list[Todo]) -> str:
    """Generate .todos.md content for a project."""
    # Filter out archived
    todos = [t for t in todos if t.status != Status.ARCHIVED]

    lines = [
        "<!-- AUTO-GENERATED by todo CLI - Do not edit manually -->",
        "",
        f"# Project TODOs: {project_name}",
        "",
    ]

    if not todos:
        lines.append("No open TODOs for this project.")
        return "\n".join(lines) + "\n"

    groups = {
        Status.IN_PROGRESS: "In Progress",
        Status.TODO: "Todo",
        Status.DONE: "Done",
    }

    for status, heading in groups.items():
        group = sorted(
            [t for t in todos if t.status == status],
            key=lambda t: t.priority,
        )
        if not group:
            continue

        lines.append(f"## {heading} ({len(group)})")
        for t in group:
            if t.status == Status.DONE:
                entry = f"- [{t.id}] ~~{t.title}~~"
                if t.completed_at:
                    entry += f" — Completed: {t.completed_at.strftime('%Y-%m-%d')}"
            else:
                entry = f"- [{t.id}] **{t.title}** — Priority: {t.priority.label}"
                if t.due_date:
                    entry += f" — Due: {t.due_date}"
                if t.tags:
                    entry += f" — Tags: {', '.join(t.tags)}"
            lines.append(entry)
        lines.append("")

    return "\n".join(lines) + "\n"


_FILE_NAMES: dict[str, dict[bool, str]] = {
    "claude": {True: "claude.local.md", False: "CLAUDE.md"},
    "agents": {True: "AGENTS.local.md", False: "AGENTS.md"},
}


def generate_llm_file_sections(
    project_root: Path,
    *,
    open_count: int,
    critical_count: int,
    llm_files: list[str],
    llm_files_local: bool,
) -> None:
    """Inject or update TODO section in configured LLM files."""
    section_lines = [
        BEGIN_SENTINEL,
        "## Project TODOs",
        f"This project has **{open_count} open** TODOs"
        + (f" ({critical_count} critical)" if critical_count else "")
        + ". See `.todos.md` for the full list.",
        "Run `todo list` for details or invoke the `/grab-todos` skill.",
        END_SENTINEL,
    ]
    section = "\n".join(section_lines) + "\n"

    pattern = re.compile(
        rf"{re.escape(BEGIN_SENTINEL)}.*?{re.escape(END_SENTINEL)}\n?",
        re.DOTALL,
    )

    for file_key in llm_files:
        names = _FILE_NAMES.get(file_key)
        if names is None:
            continue
        target = project_root / names[llm_files_local]

        if target.is_symlink():
            raise OSError(f"Refusing to write through symlink: {target}")

        if not target.exists():
            target.write_text(section)
            continue

        content = target.read_text()
        if pattern.search(content):
            content = pattern.sub(section, content)
        else:
            if not content.endswith("\n"):
                content += "\n"
            content += "\n" + section

        target.write_text(content)
