"""Project detection, .todos.md generation, CLAUDE.md updates."""

from __future__ import annotations

import os
import re
from pathlib import Path

from todo.models import Status, Todo

BEGIN_SENTINEL = "<!-- BEGIN TODO CLI -->"
END_SENTINEL = "<!-- END TODO CLI -->"


def detect_project(cwd: Path, projects_roots: list[str]) -> str | None:
    """Detect project name from cwd based on configured project roots."""
    cwd = cwd.resolve()
    for root in projects_roots:
        root_path = Path(os.path.expanduser(root)).resolve()
        try:
            rel = cwd.relative_to(root_path)
        except ValueError:
            continue
        # First component under the root is the project name
        parts = rel.parts
        if parts:
            return parts[0]
    return None


def generate_todos_md(project_name: str, todos: list[Todo]) -> str:
    """Generate .todos.md content for a project."""
    # Filter out archived
    todos = [t for t in todos if t.status != Status.ARCHIVED]

    lines = [
        "<!-- AUTO-GENERATED by todo CLI - Do not edit manually -->",
        "",
        f"# Project TODOs: {project_name}",
        "",
    ]

    if not todos:
        lines.append("No open TODOs for this project.")
        return "\n".join(lines) + "\n"

    groups = {
        Status.IN_PROGRESS: "In Progress",
        Status.TODO: "Todo",
        Status.DONE: "Done",
    }

    for status, heading in groups.items():
        group = sorted(
            [t for t in todos if t.status == status],
            key=lambda t: t.priority,
        )
        if not group:
            continue

        lines.append(f"## {heading} ({len(group)})")
        for t in group:
            if t.status == Status.DONE:
                entry = f"- [{t.id}] ~~{t.title}~~"
                if t.completed_at:
                    entry += f" — Completed: {t.completed_at.strftime('%Y-%m-%d')}"
            else:
                entry = f"- [{t.id}] **{t.title}** — Priority: {t.priority.label}"
                if t.due_date:
                    entry += f" — Due: {t.due_date}"
                if t.tags:
                    entry += f" — Tags: {', '.join(t.tags)}"
            lines.append(entry)
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_claude_md_section(
    claude_md_path: Path, *, open_count: int, critical_count: int
) -> None:
    """Inject or update TODO section in CLAUDE.md."""
    section_lines = [
        BEGIN_SENTINEL,
        "## Project TODOs",
        f"This project has **{open_count} open** TODOs"
        + (f" ({critical_count} critical)" if critical_count else "")
        + ". See `.todos.md` for the full list.",
        "Run `todo list` for details or invoke the `/grab-todos` skill.",
        END_SENTINEL,
    ]
    section = "\n".join(section_lines) + "\n"

    if not claude_md_path.exists():
        claude_md_path.write_text(section)
        return

    content = claude_md_path.read_text()

    pattern = re.compile(
        rf"{re.escape(BEGIN_SENTINEL)}.*?{re.escape(END_SENTINEL)}\n?",
        re.DOTALL,
    )
    if pattern.search(content):
        content = pattern.sub(section, content)
    else:
        if not content.endswith("\n"):
            content += "\n"
        content += "\n" + section

    claude_md_path.write_text(content)
